name: subdivisions
channels:
  - conda-forge
dependencies:
  - python=3.12.7
  - geemap
  - geopandas
  - osmnx
  - coiled
  - jupyterlab
  - jupyter-server-proxy
  - python-graphviz
  - overturemaps
  - earthengine-api
  - google-cloud-sdk
